#!/usr/bin/env bash
# Script that loops from 1 to 10 and performs an action at some points

i=1
while (( "$i" <= 10 ))
do
	if (( "$i" == 4 ))
	then
		echo "bad luck"
	elif (( "$i" == 8 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
