#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes

h=0
m=1

while (( "$h" <= 12 ))
do
	echo "Hour: $h"
	m=1
	while (( "$m" <= 59 ))
	do
		echo "$m"
		(( m++ ))
	done
	(( h++ ))
done
