#!/usr/bin/env bash
# Displays the content of the current dir,
#+ in a list format
#+ where only the part of the name after the first dash is displayed

for i in *
do
	echo "$i" | cut -d '-' -f 2;
done
