#!/usr/bin/env bash
# change localhost to 127.0.0.2
# append facebook.com resolving to 8.8.8.8
# make a copy of the original hosts file
cp /etc/hosts /etc/hosts.original
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/  ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
